language: scala
scala:
  - 2.11.7
jdk: oraclejdk8
sudo: false
cache:
  directories:
  - $HOME/.ivy2/cache
before_install:
  - curl https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/2.4.1/elasticsearch-2.4.1.tar.gz | tar xz --directory=$HOME
  - $HOME/elasticsearch-2.4.1/bin/plugin install 'http://repo1.maven.org/maven2/org/xbib/elasticsearch/plugin/elasticsearch-plugin-bundle/2.4.1.0/elasticsearch-plugin-bundle-2.4.1.0-plugin.zip'
  - $HOME/elasticsearch-2.4.1/bin/elasticsearch --daemonize --path.data /tmp && sleep 20s
install:
  - cd node/json-frame/ && npm install && cd ../..
before_script:
  - cp conf/travis.conf conf/test.conf
  - (node node/json-frame/frame.js 8080 conf/context.json https://oerworldmap.org/assets/json/context.json &) && sleep 5s
branches:
  only:
    - master
